### ISSUE TITLE
stats view problem and some wrong upgrades

### ISSUE THREAD

**Issue by Zay36** [System-Glitch/Unit-Stat-Utility#15]
**The stats value** for _armors and gathering_ rate should have two digits and _the conversion rate_ of priests should decrease after their upgrade.
**Babylonian:** _royal guard champion_ upgrade increase damage by 50% which is only shown as an increase in attack rate in the tool.
**Persian:** _rigorous training_ doesn't apply to immortals, rams, war wagon, and palintonon.
and _barrack's upgrades_ don't apply to immortals.
![units stats](https://user-images.githubusercontent.com/45094443/48615703-af4f8c80-e9a2-11e8-8ddc-cdfc672b5e9c.png)

**Comment by System-Glitch** [comment]
Relentless Zeal is also wrong. It should apply only to Immortal Camp, Siege Workshop, and Fortress.
