### ISSUE TITLE
Add a database for all advisors

### ISSUE THREAD

**Issue by ByFstugan** [System-Glitch/Unit-Stat-Utility#19]
There is an awesome database for all items (need som update with namechanges from "divine..." and adding the event items) and the awesome statistics page for units stats, but there is no such page for advisors. There is an old wiki page that's pretty good, but since new content has come it's out of date (and I think some advisors has been changed, at least some of the new has), here is the old page: https://ageofempiresonline.fandom.com/wiki/Advisor 

...something similar and up2date would be great so people can see if they have all advisors or not.

**Comment by System-Glitch** [comment]
This repository is only about the unit stat utility. This demand is unrelated. Feel free to suggest it on the forums or on discord.
